### ISSUE TITLE
/etc/autoupdatehosts: line 37: iconv: not found

### ISSUE THREAD

**Issue by jalousiex** [Aethersailor/OpenWrt-AutoUpdateHosts#1]
缺少个依赖，建议安装时处理

**Comment by jalousiex** [comment]
iconv: conversion from ANSI unsupported
iconv: try 'iconv -l' to get the list of supported encodings

**Comment by Aethersailor** [comment]
> iconv: conversion from ANSI unsupported
> 
> iconv: try 'iconv -l' to get the list of supported encodings

暂时取消了转换文件编码的步骤，不会再报错了
